# Generated by Django 5.1.1 on 2024-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="percentage_completion",
            field=models.IntegerField(default=0),
        ),
    ]
