# Generated by Django 5.1.1 on 2024-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_todo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
