# Generated by Django 5.1.1 on 2024-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_todo_archived_at_alter_todo_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="slug",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("done", "done"),
                    ("in-progress", "in-progress"),
                ],
                default="new",
                max_length=200,
            ),
        ),
    ]
